name: mvcflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  provider: ^6.1.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.10
  email_validator: ^3.0.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  package_info_plus: ^8.1.2
  dio: ^5.9.0
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.10
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^8.0.0

dependency_overrides:
  shared_preferences_android: 2.4.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/public/assets/images/
    - lib/public/assets/logo/
