name: mvcflutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Hot load pages using named routes
  go_router: ^16.2.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  provider: ^6.1.2
  firebase_auth: ^5.3.4
  email_validator: ^3.0.0
  connectivity_plus: ^6.0.5
  app_settings: ^5.1.1
  cloud_firestore: ^5.6.10
  video_player: ^2.9.2
  permission_handler: ^12.0.0+1
  flutter_cache_manager: ^3.4.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  grouped_list: ^6.0.0
  intl: ^0.20.1
  package_info_plus: ^8.1.2
  image_picker: ^1.1.2
  camera: ^0.11.1
  file_picker: ^10.2.0
  video_compress: ^3.1.3
  path_provider: ^2.1.5
  dio: ^5.7.0
  auto_size_text: ^3.0.0
  icons_launcher: ^3.0.0
  saver_gallery: ^4.0.1
  fluttertoast: ^8.2.10
  tmp_path: ^1.3.3
  simple_connection_checker: ^0.3.4
  firebase_storage: ^12.4.7
  google_maps_flutter: ^2.12.1
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  app_links: ^6.4.0
  flutter_slidable: ^4.0.0
  firebase_database: ^11.3.3
  url_launcher: ^6.3.1
  sensitive_content_analysis: ^1.1.1
  better_player: ^0.0.84
  video_editor_2: ^3.1.1
  videosdk_media_effects: ^0.0.3
  flutter_gpu_video_filters: ^0.0.20
  # Force newer video_thumbnail to reduce deprecated API usage in transitive deps
  video_thumbnail: ^0.5.3
  camerawesome: ^2.5.0
  flutter_awesome_reels: ^0.0.4
  story_view: ^0.16.6
  just_audio: ^0.10.4
  record: ^6.0.0
  easy_video_editor: ^0.1.2
  badges: ^3.1.2
  flutter_svg: ^2.2.0
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.5
  confetti: ^0.8.0
  geocoding: ^4.0.0
  http: ^1.4.0
  geolocator: ^14.0.2
  fc_native_video_thumbnail: ^0.17.2
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^15.1.6
  video_editor: ^3.0.0
  flutter_riverpod: ^3.0.0
  syncfusion_flutter_pdfviewer: ^30.1.42
  ffmpeg_kit_flutter_new: ^3.2.0
  flutter_secure_storage: ^8.0.0
  scrollable_positioned_list: ^0.3.8
  flutter_linkify: ^6.0.0
  any_link_preview: ^3.0.3
  emoji_picker_flutter: ^4.3.0
  hive_flutter: ^1.1.0
  pdf: ^3.11.0
  omni_datetime_picker: ^2.3.1

dependency_overrides:
  shared_preferences_android: 2.4.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  mockito:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

icons_launcher:
  image_path: 'asset/logo/logo.jpeg'
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - asset/images/
  - asset/logo/
  - lib/assets/VideoUploadPage/
  - asset/svg/
  # - asset/terms_and_policy/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
